# Generated by Django 6.0 on 2025-12-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidad', models.CharField(max_length=100)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('temp_max', models.FloatField()),
                ('temp_min', models.FloatField()),
                ('lluvia', models.FloatField()),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
